<?php
return [
  [
    'title' => '首页',
    'icon' => '',
    'module' => 'system',
    'url' => 'system/index',
    'param' => '',
    'target' => '_self',
    'debug' => 0,
    'system' => 1,
    'nav' => 1,
    'sort' => 0,
    'childs' => [
      [
        'title' => '快捷菜单',
        'icon' => 'aicon ai-caidan',
        'module' => 'system',
        'url' => 'system/quick',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 1,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 1,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 1,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 1,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 2,
            'childs' => [
              [
                'title' => '设置默认等级',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/member/setdefault',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 0,
              ],
              [
                'title' => '重置密码',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/member/resetPwd',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 6,
              ],
            ],
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 2,
          ],
          [
            'title' => '清空缓存',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/index/clear',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 0,
            'sort' => 2,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 2,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 3,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 4,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 4,
          ],
          [
            'title' => '个人信息设置',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/user/info',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 0,
            'sort' => 5,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 5,
          ],
          [
            'title' => '后台首页',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/index/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 0,
            'sort' => 100,
          ],
          [
            'title' => '后台首页',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/index/welcome',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 0,
            'sort' => 100,
          ],
          [
            'title' => '布局切换',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/user/iframe',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 0,
            'sort' => 100,
          ],
          [
            'title' => '钩子插件状态',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/hook/hookPluginsStatus',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 0,
            'sort' => 100,
          ],
          [
            'title' => '设置主题',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/user/setTheme',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 0,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
        ],
      ],
      [
        'title' => '产品管理',
        'icon' => 'aicon ai-gongneng',
        'module' => 'system',
        'url' => 'system/product/index',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '产品列表',
            'icon' => 'typcn typcn-th-menu-outline',
            'module' => 'system',
            'url' => 'system/product/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '添加',
                'icon' => 'aicon ai-tianjia',
                'module' => 'system',
                'url' => 'system/product/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/product/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '原料分析',
        'icon' => 'fa fa-newspaper-o',
        'module' => 'system',
        'url' => 'system/material/index',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '分析列表',
            'icon' => 'fa fa-calculator',
            'module' => 'system',
            'url' => 'system/material/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '添加',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/material/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/material/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '到货登记',
            'icon' => 'aicon ai-caidan',
            'module' => 'system',
            'url' => 'system/delivery/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '添加',
                'icon' => 'aicon ai-tianjia',
                'module' => 'system',
                'url' => 'system/delivery/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 1,
                'sort' => 0,
              ],
              [
                'title' => '编辑',
                'icon' => 'aicon ai-gou',
                'module' => 'system',
                'url' => 'system/delivery/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 1,
                'sort' => 0,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '供应商管理',
        'icon' => 'aicon ai-tubiao05',
        'module' => 'system',
        'url' => 'system/supplier/index',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '供应商列表',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/supplier/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '添加',
                'icon' => 'aicon ai-tianjia',
                'module' => 'system',
                'url' => 'system/supplier/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 1,
                'sort' => 0,
              ],
              [
                'title' => '编辑',
                'icon' => 'aicon ai-tianjia',
                'module' => 'system',
                'url' => 'system/supplier/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 1,
                'sort' => 0,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '询价',
        'icon' => 'aicon ai-mokuaiguanli',
        'module' => 'system',
        'url' => 'system/inquiry/index',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '询价列表',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/inquiry/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '添加',
                'icon' => 'aicon ai-gou',
                'module' => 'system',
                'url' => 'system/inquiry/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 1,
                'sort' => 0,
              ],
              [
                'title' => '编辑',
                'icon' => 'aicon ai-daochu',
                'module' => 'system',
                'url' => 'system/inquiry/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 1,
                'sort' => 0,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '采购',
        'icon' => '',
        'module' => 'system',
        'url' => 'system/purchase/index',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '采购列表',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/purchase/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '添加',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/purchase/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 1,
                'sort' => 0,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/purchase/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 1,
                'sort' => 0,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '投诉',
        'icon' => '',
        'module' => 'system',
        'url' => 'system/complaint/index',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '投诉列表',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/complaint/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '添加',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/complaint/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 1,
                'sort' => 0,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/complaint/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 1,
                'sort' => 0,
              ],
            ],
          ],
        ],
      ],
    ],
  ],
];
